version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_TM
    restart: always
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: task_manager_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_manager
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: